services:
  php:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../src:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../../src:/var/www
      - ../../nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
