services:
  app:
    image: dunglas/frankenphp:1.2-php8.3
    container_name: myapp-php
    restart: unless-stopped

    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

    environment:
      APP_ENV: production
      APP_DEBUG: "false"

    # PENTING: jangan expose 80
    ports:
      - "127.0.0.1:8080:80"

    networks:
      - internal

networks:
  internal:
    driver: bridge