services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      # Konfigurasi worker mode via environment variable
      - FRANKENPHP_CONFIG="worker public/index.php"
      # FORCE HTTP ONLY (Non-HTTPS) so Caddy doesn't redirect. Important for Nginx Proxy Manager / Cloudflare behind proxy.
      - SERVER_NAME=:80
    command: "--port=80 --host=0.0.0.0"
    volumes:
      - .:/app
      - /app/vendor # PENTING: Jangan timpa vendor dari image dengan folder host yang kosong
      - /app/bootstrap/cache # PENTING: Gunakan cache bawaan container, jangan dari host yang corrupt/stale
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - myapp-net
      - npm_net # Connect to NPM network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  myapp-net:
    driver: bridge
  npm_net:
    external: true
    name: my-stack_my-network # Nama network external NPM kamu
