services:
  app:
    container_name: myapp-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    networks:
      - my-stack_my-network
    expose:
      - "8000"

  nginx:
    container_name: myapp-nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/public
    depends_on:
      - app
    networks:
      - my-stack_my-network
    expose:
      - "80"

networks:
  my-stack_my-network:
    external: true