services:
  php:
    image: laravel-app
    container_name: laravel-php
    restart: always
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - ../../nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    networks:
      - laravel_net

networks:
  laravel_net:
    external: true
